/**
 * GET /api/orders/lookup
 *
 * Hardened order lookup supporting:
 *   - Legacy codes:  ^NK\d{6}$          (e.g. NK123456)
 *   - New codes:     ^[UNAMBIGUOUS]{8}$  (8-char server-generated codes)
 *
 * Usage:
 *   /api/orders/lookup?code=ABCD1234          → single lookup
 *   /api/orders/lookup?codes=ABCD1234,XY56... → batch lookup (max 30)
 *
 * Security:
 *   - Malformed and non-existent codes return the same 404 to prevent
 *     enumeration or format fingerprinting.
 *   - Per-IP sliding-window in-memory rate limit (60 req / 60 s).
 *     NOTE: In-memory limiting is best-effort on stateless serverless
 *     environments (e.g. Netlify). The primary brute-force protection is
 *     the ~1.1 trillion possible 8-character codes from the unambiguous
 *     alphabet, making random enumeration computationally infeasible.
 *   - Batch codes that fail format validation are silently dropped.
 */

import { NextRequest, NextResponse } from 'next/server';
import { createAdminClient } from '@/lib/supabase-server';
import type { SupabaseEnv } from '@supabase/server';

// ─── Env helper ──────────────────────────────────────────────────────────────

function resolveEnv(): Partial<SupabaseEnv> {
  const url = process.env.NEXT_PUBLIC_SUPABASE_URL;
  const publishableKey =
    process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY ||
    process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY;
  const secretKey = process.env.SUPABASE_SECRET_KEY;

  const env: Partial<SupabaseEnv> = {};
  if (url) env.url = url;
  if (publishableKey) env.publishableKeys = { default: publishableKey };
  if (secretKey) env.secretKeys = { default: secretKey };
  return env;
}

// ─── Code format validation ───────────────────────────────────────────────────

// Legacy format generated by the old client-side generateOrderCode()
const LEGACY_CODE_RE = /^NK\d{6}$/i;
// New format: 8 characters from the unambiguous alphabet (no 0/O/1/I/L)
const NEW_CODE_RE    = /^[23456789ABCDEFGHJKMNPQRSTUVWXYZ]{8}$/i;

function isValidCodeFormat(code: string): boolean {
  return LEGACY_CODE_RE.test(code) || NEW_CODE_RE.test(code);
}

function normalizeCode(raw: string): string {
  return raw.trim().toUpperCase();
}

// ─── Rate limiting (in-memory, best-effort on serverless) ────────────────────

const RATE_LIMIT_WINDOW_MS = 60_000;  // 60 seconds
const RATE_LIMIT_IP_MAX    = 300;     // 300 req / min across all devices on shared Wi-Fi
const RATE_LIMIT_CODE_MAX  = 20;      // 20 req / min per order code (~10-12 req/min under 6s polling)
const RATE_LIMIT_BATCH_MAX = 60;      // 60 req / min for batch requests per IP

type RateLimitEntry = { count: number; windowStart: number };
const ipWindowMap = new Map<string, RateLimitEntry>();
const targetWindowMap = new Map<string, RateLimitEntry>();

function checkRateLimit(map: Map<string, RateLimitEntry>, key: string, max: number, now: number): boolean {
  const entry = map.get(key);
  if (!entry || now - entry.windowStart > RATE_LIMIT_WINDOW_MS) {
    map.set(key, { count: 1, windowStart: now });
    return false;
  }

  entry.count++;
  return entry.count > max;
}

function cleanupStaleEntries(now: number) {
  if (ipWindowMap.size > 1000) {
    ipWindowMap.forEach((v, k) => {
      if (now - v.windowStart > RATE_LIMIT_WINDOW_MS) ipWindowMap.delete(k);
    });
  }
  if (targetWindowMap.size > 2000) {
    targetWindowMap.forEach((v, k) => {
      if (now - v.windowStart > RATE_LIMIT_WINDOW_MS) targetWindowMap.delete(k);
    });
  }
}

// ─── Projected fields (only what status/orders pages actually use) ────────────

const SELECT_FIELDS =
  'id, order_code, customer_name, table_number, branch_id, items, subtotal, total, payment_method, notes, status, created_at';

// ─── Shared 404 response (same message for invalid format + not found) ────────

function notFound() {
  return NextResponse.json(
    { error: 'Pesanan tidak ditemukan.' },
    { status: 404 },
  );
}

// ─── Handler ─────────────────────────────────────────────────────────────────

export async function GET(request: NextRequest) {
  // Rate limiting
  const ip = request.headers.get('x-forwarded-for')?.split(',')[0]?.trim()
    ?? request.headers.get('x-real-ip')
    ?? 'unknown';

  const now = Date.now();
  cleanupStaleEntries(now);

  // 1. Overall per-IP ceiling check (e.g. 300/min) so shared Wi-Fi is not blocked
  if (checkRateLimit(ipWindowMap, ip, RATE_LIMIT_IP_MAX, now)) {
    return NextResponse.json(
      { error: 'Terlalu banyak permintaan. Coba lagi sebentar.' },
      { status: 429 },
    );
  }

  const { searchParams } = new URL(request.url);
  const codesParam       = searchParams.get('codes');
  const codeParam        = searchParams.get('code');

  // 2. Specific per-(IP + order_code) check for single lookups, or per-IP batch check
  if (codeParam) {
    const normalized = normalizeCode(codeParam);
    const targetKey = `${ip}:${normalized}`;
    if (checkRateLimit(targetWindowMap, targetKey, RATE_LIMIT_CODE_MAX, now)) {
      return NextResponse.json(
        { error: 'Terlalu banyak permintaan untuk pesanan ini. Coba lagi sebentar.' },
        { status: 429 },
      );
    }
  } else if (codesParam) {
    const targetKey = `${ip}:batch`;
    if (checkRateLimit(targetWindowMap, targetKey, RATE_LIMIT_BATCH_MAX, now)) {
      return NextResponse.json(
        { error: 'Terlalu banyak permintaan. Coba lagi sebentar.' },
        { status: 429 },
      );
    }
  }

  const env            = resolveEnv();
  const supabaseAdmin  = createAdminClient({ env });

  // ── Batch lookup ────────────────────────────────────────────────────────────
  if (codesParam) {
    const validCodes = Array.from(
      new Set(
        codesParam
          .split(',')
          .map(normalizeCode)
          .filter(isValidCodeFormat),      // silently drop malformed codes
      ),
    ).slice(0, 30);                        // hard cap

    if (validCodes.length === 0) {
      return NextResponse.json({ orders: [] });
    }

    const { data: orders, error } = await supabaseAdmin
      .from('orders')
      .select(SELECT_FIELDS)
      .in('order_code', validCodes)
      .order('created_at', { ascending: false });

    if (error) {
      return NextResponse.json({ error: error.message }, { status: 500 });
    }

    return NextResponse.json({ orders: orders ?? [] });
  }

  // ── Single lookup ───────────────────────────────────────────────────────────
  const rawCode = codeParam ?? '';
  const code    = normalizeCode(rawCode);

  // Reject malformed codes with the same 404 as "not found"
  if (!code || !isValidCodeFormat(code)) {
    return notFound();
  }

  const { data: order, error } = await supabaseAdmin
    .from('orders')
    .select(SELECT_FIELDS)
    .eq('order_code', code)
    .maybeSingle();

  if (error) {
    return NextResponse.json({ error: error.message }, { status: 500 });
  }

  if (!order) {
    return notFound();
  }

  return NextResponse.json({ order });
}
